name=input("enter your name: ")
age=input("enter your age: ")
city=input("where do you live: ")
college=input("enter your college name: ")
course=input("enter your course name: ")
semester=input("enter your semester: ")
fav_subject=input("which is your fav subject: ")
career_goal=input("what's your career goal: ")

print("hello myself",name)
print("i'm",age,"years old")
print("i live in",city)
print("my college name is",college,"and it is beautiful")
print("currently i'm studying",course,"and i'm in",semester)
print("my fav subject is",fav_subject,"i love it")
print("i want to become an",career_goal,"i'm fully locked in for it")
